### ISSUE TITLE
Construction pattern refactoring

### ISSUE THREAD

**Issue by mike1813** [Spyderisk/domain-network#183]
As discussed in issue #169, to improve modularity it makes sense to replace the explicit construction sequence by a set of construction pattern dependencies, leaving csv2nq to compute a partial ordering of construction patterns that can be inserted into the NQ file used by system modeller.

One side-effect of doing this is that the explicit sequence number stored for each construction pattern in field hasPriority, table ConstructionPattern.csv is no longer meaningful. It makes sense to change the canonical ordering of ConstructionPattern.csv, so this is based on the package membership, then the URI of each pattern. Doing this would mean concurrent changes to different packages can in future be more easily handled by git merge, and make it possible to apply filtering in csv2nq, such that optional packages included in the domain model source code can be excluded from the NQ file.

The only downside is that it isn't possible to use git merge to combine changes if one set of changes is on a branch that uses the old canonical ordering and the other uses the new canonical ordering.

To fix this, we should freeze development of all branches briefly, and make one further change to the head of each active branch that still uses the old ordering. This change should change the ordering used in table ConstructionPattern.csv, and make no other changes. One slight issue is that the MS Access DB domain model editor uses a native MS Access sort order, which is not guaranteed to be the same as the native MS Excel sort order. So the precise definition of this sort order should also be specified somewhere.

The branches that need this treatment are as follows:

- [ ] branch 6a: currently the main 'dev' branch in this repository
- [ ] branch 132: contains an optional 'patient harms' model
- [ ] branch 170: contains an optional 'harms arising in AI (specifically ML) systems.
- [ ] branch 176: has construction pattern dependencies inherited from branch 169, plus an extensions to the network connectivity and application models needed by project TELEMETRY.

Branch is 176 was created from branch 169, in which the reordering of ConstructionPattern.csv has already been done. However, the new canonical ordering may be different from this due to the adoption of a specified sort order in place of the MS Access native sort order, so a new update should also be made here:

Once this has been done, it would be possible to merge branches 132, 170 and 176 into branch 6a, or (if preferred) a new 'dev' branch that uses the new canonical ordering in all the CSV tables. The extensions in branch 176 are not optional (all are changes to the base domain model), so this needs doing anyway. The extensions in branches 132 and 170 are considered optional at present, but once we have the new canonical ordering and csv2nq filtering capability, there is no disadvantage to having them all in the same source tree.

**Comment by mike1813** [comment]
Did some experiments to check how the MS Access DB sorts string-valued fields (like those in the 'package' and 'URI' fields we use most often for this purpose). It turns out that by default, MS Access ignores the case of alphabetic characters, and pretty much any other non-alphabetic but printable character in the basic set comes before the alphabetic characters.

This gives a different outcome from almost any other lexicographic sort function, so we need to change it.

The new convention is that strings are sorted on their characters in the order they appear in the string, and the rank of each character is the corresponding ASCII or Unicode value by which it is represented. This means that:

- sorting is case sensitive, with all upper case letters ranked before any lower case letters
- digits come before upper case letters
- punctuation characters are in four blocks: before digits, between digits and upper case letters, between upper and lower case letters, and after lower case letters
- the space character is before all other characters, but it is ignored if it appears at the end of a string (i.e., space characters are used to rank the string only if they are at the start or in the middle of other, printable characters).

The MS Access DB script to export tables has now been altered so it complies with this specification, although it does mean that the proposed changes will now affect the ordering of more tables than we previously thought, where case sensitive sorting leads to a different row order than case insensitive sorting.

**Comment by mike1813** [comment]
I created the branches, but mistakenly associated them with issue 180.

**Comment by mike1813** [comment]
In branch 176 (actually in branch 169), packages that contain only construction patterns have been merged with the corresponding packages that create threats and other stuff. This is necessary because construction-only packages are on different branches of the package dependency hierarchy, so it is not possible for one construction pattern to have a property referring to another from a different package.

The problem is that the canonical ordering for most CSV tables is based on the package URI before anything else. This means the reordering in branches 6a, 132 and 170 must also involve merging construction-only packages with the packages containing related threats and other stuff.

**Comment by mike1813** [comment]
There are also two potentially significant change in the package dependency hierarchy in branch 176.

The first change is that in other branches, package#Network depends on package#Core, whereas in branch 176, package#Users depends on package#Core. The dependence of package#Network on package#Core was asserted at a time when package#Network formed the bottom of the trunk in the package dependency tree, so making it depend on package#Core implied all other packages also depend on package#Core. However, at some point package#Network was made to depend on package#AccessContext and by implication also package#Physical and package#Users. Moving these packages below package#Network meant their dependence on package#Core was no longer implied by their asserted (direct) dependencies. To fix this, the dependence on package#Core was moved from package#Network to package #Users.

This change should obviously have been made in other branches, so it will be included in the reordering updates. This also means that the package rankings should be recalculated. That was not done in branch 176, so that change will now be added in branch 176.

The second change is that in other branches, package#5G depends on package#NetworkConnectivity, whereas in branch 176, package#5G depends on package#Virtualisation. This change was needed because there are dependencies between construction patterns in package#5G and package#Virtualisation. Having them on separate branches of the package hierarchy meant it was not possible to add properties to the construction patterns in either package which referred to patterns in the other package.

There are no dependencies of patterns in either package on assets, roles or relationships from the other package, so this change is not needed until CP dependencies are added. For that reason it will not be included in the other branches.

**Comment by mike1813** [comment]
Discussion between @mike1813 and @samuelsenior  concluded that the best way to proceed is as follows:

- [ ] Create side-branches off branches 6a, 132, 170 and 176.
- [ ] On the side-branches off 6a, 132, 170, just fix the package assignments so there is no separation between construction patterns and other entities in each sub-model, and export in the new canonical order. This should make it possible to merge these branches along with the branch off 176, because all four will be using the same canonical ordering.

On the branch off 176, other issues should be fixed, including:

- [ ] Issue #171: fixing the sequencing error for CNS+RAN+BS-S+l.
- [ ] Issues #172 and #173: fix fix underspecification of nodes  in some K8S cloud management patterns.
- [ ] Issue #174: fix underspecification of nodes in some IoT patterns.
- [ ] Issue #182: add flags to Packages.csv table, to specify which packages should be included/excluded when converting to NQ
- [ ] 
Then fix any other residual issues that create difficulties and produce a suitable set of CP dependencies.

Then finally:

- [ ] Merge the side-branches off 6a, 132 and 170 into the side-branch created off 176. This should lead to a single branch with all the sub-models included.
- [ ] Merge this into the main branch.
- [ ] Create a new 'dev' branch off the main branch, and in future use this as the main trunk for current development work, so the repository becomes more 'conventional' in its use of branches.
- [ ] Create sub-branches off this in as necessary to create releases, where the only changes are to alter which packages are included.

Thus we can create a domain model for use in (say) the EU NEMECYS project that includes Patient Harms and GDPR, without maintaining a separate branch for those developments. The development of these optional submodels can still be merged into the 'dev' branch, even if at some stage it is decided they should be deselected by default.

**Comment by mike1813** [comment]
This got out of control. After fixing the sequencing errors discussed in #171, loops appeared on the CP dependency graph.

The reason this happens is because the construction pattern dependencies were initialised using the following automated process:

1. Create-then-match or match-then-create dependencies were found, by detecting cases where assets or links created by one pattern would match assets or links in the matching pattern of another.
2. For each pair of dependent patterns, the order of execution was found by comparing the values of their hasPriority properties.
3. Package dependencies were then consulted to determine whether the dependency should be encoded as a ConstructionPredecessor or ConstructionSuccessor entry. The idea is that these tables insert a reference to one pattern as a property of another. However, references from one pattern should only be to patterns in the same package or a package on which this depends.
4. Dependencies that can be inferred as a sequence of other such dependencies were eliminated, i.e., if A precedes B precedes C then we don't need A precedes C. However, this can only be done where all three relationships (A-B, B-C and A-C) can be made consistent with package dependencies.

The problem with this (unforeseen at the time) is that the original construction sequence encoded via hasPriority values contains a lot of interleaving between subsequences from other packages. It is not possible to alter the sequence on one package without creating consequences in another package. The reason this happens is that the interleaving between packages reflects the ordering within each package. One can't change the ordering in one package without also changing the interleaving links, and this often forces changes in the ordering in other packages to keep everything consistent. Without this, one gets loops (meaning some patterns can never be reached), or unexpected sequencing errors which appear in any affected package (not just the one where the order was initially changed).

The only reasonable way to resolve this is to create a new starting position, by starting with no ConstructionPredecessor or ConstructionSuccessor entries, and building them up one package at a time. The idea is that the ordering is determined in each package, and specified by creating entries within that package, or with patterns in other packages on which it depends (whose order is not changed). Then it is possible to move on to dependent packages. So one should start with (say) package#Physical, then package#Users, then package#Network and so forth.

It turns out that the overall structure is dictated by package#Network. However, the interleaving in the original sequence meant parts of this structure were not specified in package#Network, but arose only because of interleaving with sequences from other packages like package#NetworkConnectivity, package#Virtualisation or package#5G. This is why the changes in package#5G to address issue #171 led to lots of unexpected problems. It is also worth noting that in some places the ordering in package#Network was not properly specified.

By creating predecessor and successor relationships manually from scratch, each package building on the last, it should be possible to get the structures right.
