### ISSUE TITLE
Bugs in reverse proxy inference patterns

### ISSUE THREAD

**Issue by mike1813** [Spyderisk/domain-network#47]
A reverse proxy is a service whose purpose is to provide an accessible endpoint for a 'back-end' service. Instead of accessing the back-end service directly, clients connect to the proxy which forwards requests to the service.

There are two modes in which a proxy could operate:

- An authenticating proxy: the client authenticates with the proxy, and the proxy authenticates as itself to the back-end service. The proxy opens a session from the client after the client has successfully authenticated, then forwards subsequent requests to the service. It doesn't forward the client authentication request to the service.
- A transparent proxy: the proxy forwards all requests from the client to the back-end service, including the initial authentication request. The back-end service authenticates the client, and its response via the proxy tells the proxy whether to open a session from that client, If authentication is successful, a session is opened from the client to the proxy which forwards subsequent requests to the service.

The difference between these two is important for security. With a transparent proxy, services manage their own users, but this means a request can be sent without authentication. Some anonymous attacks could therefore be carried out via the proxy on a back-end service. On the other hand, not forwarding authentication requests means the proxy could in principle access any back-end service on behalf of any of its clients. In principle, each client should only send requests to back-end services they need to use, but there is nothing stopping untrustworthy clients requesting other services they don't need.

To control access to back-end services one would use something like OAuth 2.0, a common OAuth server controlling access to the proxy (via a redirected authentication) and back-end services (by issuing authorization codes or access tokens for specific back-end resources only). The existing model of OAuth 2.0 in v6a3-2-2 only covers the implicit flow, and only covers back-end services if the front-end service acts as a transparent proxy. (Note that the existing model covers the OAuth 2.0 interactions, but doesn't assume the implementation complies with teh OAuth 2.0 standard).

An upgrade of this model is therefore currently under development. As a first step, baseline tests were run using v6a3-2-2, which revealed some bugs in the inference patterns related to reverse proxies.

The first bug is an error in the inference sequence for authenticating proxies. In principle, there should be a mediated 'Client-uses-Service' between clients and the services they need to access, where this 'uses' relationship is either:

- asserted by the system-modeller user when defining the system model, or
- inferred from an analysis of data flow dependencies between the Client and back-end Services

The bug means that the Client-uses-Service relationship is not inferred from data flow dependencies if the Client is authenticated by the Proxy. The correct relationships to back-end Services must be asserted by the system-modeller user, and if this is not done some threats may be missed.

The workaround for system-modeller users is to ensure they do assert all such 'indirect' Client-Service relationships where they go via an authenticating proxy.

The second bug arises when there is a Client accessing a Service via a transparent proxy, and access to the Service is controlled by an OAuth-style authorization service. The Client would then be redirected to the authorization service for authentication, and then back to the Service. If the authorization service is accessed via the same proxy, this can be indicated by asserting that the Proxy-usesForAuth-AuthService. This should trigger an inference pattern to specify that the authorization service therefore controls the proxy, creating a uses-><-controls loop between the Proxy and AuthService in general means the former forwards transparently through to the latter. However, there is a sequencing error, so this inference is not made until after it is needed.

The workaround for system-modeller users is to explicitly add the AuthService-controls-Proxy relationship as well as the Proxy-usesForAuth-AuthService, wherever they need to specify that the AuthService is accessed via a transparent proxy.

The third bug occurs if there is a Client accessing a Service via a transparent proxy, and access to the proxy is controlled by some other AuthService via an OAuth-style AuthService-controls-Proxy that is not also accessed via the proxy. This situation could be asserted by a system-modeller user, but it makes no sense as access to the Proxy to each of its back-end services would then be controlled by both the back-end service and a separate AuthService. The results of the construction and threat inference therefore also makes no sense. We should get a modelling error, but v6a3-2-2 doesn't have one for this situation.

There is no workaround for system-modeller users except to avoid making this error. Few would recognise it as such, so we need a new modelling error threat.

Note that it might not be an error to have two authorization services controlling access to a service that is not a transparent proxy. It is perfectly possible to configure a service to accept access tokens or authorization codes from two different OAuth-style services. We might want a modelling error to detect this situation as well, but in that case the modelling error should have a control strategy to signal that multiple OAuth-style controls relationships was deliberate.

Finally, threats that today use matching patterns containing required or prohibited 'controls' links will need to be reviewed, and these links replaced by other inferred links that distinguish between scenarios (redirection to an OAuth-style authenticator, or forwarding by a proxy to a back-end service). This will make it possible to introduce more variations in the use of the 'controls' links to handle the Authorization Code flow, and new inferred link types to distinguish them from the Implicit flow and proxy variations.

These issues should be fixed as part of the OAuth 2.0 model upgrades currently being developed:

- [x] Issue #48, fix the sequence to infer indirect access by clients to back-end services via one or more proxies of either type.
- [x] Issue #49, fix the sequencing error that prevents inference of control over access to a back-end authorization service if accessed via a transparent proxy.
- [x] Issue #50, add a modelling error threat to detect competing control over a transparent proxy.
- [x] Issue #56, revamp threats for access via proxies.
- [x] Issue #60, review the use of 'controls' links in threat patterns and substitute scenario-specific inferred links.

**Comment by mike1813** [comment]
Not raising a pull request for 6a <- branch 47 because regression tests found several other issues which should be covered first. They will be tackled in a separate branch, but I will start by merging changes from branch 47, and then raise a pull request once those other issues have been addressed.

**Comment by mike1813** [comment]
Now closing this issue.
