### ISSUE TITLE
Remote access and data flow reconciliation

### ISSUE THREAD

**Issue by mike1813** [Spyderisk/domain-network#65]
Issue #47 described a number of problems with the way remote access via proxies was being handled, which needed fixing before we can extend the OAuth/OIDC authentication and authorization model.

Regression tests while tackling issue #47 revealed some other problems with threats caused or affecting client-service relationships (Client Channels), including threats involving data flows. To resolve the remaining problems with remote access threats, we need to address these further issues:

- [x] Issue #51: bugs in service impersonation threats blocks creation of some valid threats to service authenticity.
- [x] Issue #52: bug in data flow construction patterns cause spurious 'reverse' data flows via at least two transparent proxies.
- [x] Issue #55: missing CASettings cause some controls to be unavailable at (among other asset types) reverse proxies, leading to an inappropriate inability to address some threats, and a failure to find others that depend on those controls.
- [x] Issue #63: messy sequencing issue whereby inference related to remote access (to a host) is processed before access via proxies.
- [x] Issue #64: rationalising threats to Client Channel TW attributes related to client access.
- [x] Issue #67: bug in the threat from access to a compromised service, which doesn't cover access via a transparent proxy.
- [x] Issue #68: review and fix issues in threats causing or caused by Client/Service Authenticity or TW.
- [ ] Issue #53: review and fix issues in threats causing data flow or data request overloads.

**Comment by mike1813** [comment]
Mostly addressed in branch 85. The remaining aspect is covered by issue #53, so this issue can now be closed.
